baseURL = "http://madsholfort.dk"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "cocoa" 
publishDir = "docs"

[params]

extracssfiles          = [ "/css/override.css" ]



[[menu.main]]
name                   = "Forside"
weight                 = -120
identifier             = "forside"
url                    = "/" 




[[menu.main]]
name                   = "Portfolio"
weight                 = -120
identifier             = "portfolio"
url                    = "/portfolio/"





[[menu.main]]
name                   = "Blog"
weight                 = -120
identifier             = "blog"
url                    = "/blog/"


[[menu.main]]
name                   = "Kontakt"
weight                 = -120
identifier             = "contact"
url                    = "/contact/"


[[menu.main]]
name                   = "About"
weight                 = -120
identifier             = "about"
url                    = "/about/"

